FROM python:3.10

WORKDIR /app

COPY app.py .
COPY modelo_tiroides.pkl .
COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 8001

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]