FROM python:3.10

WORKDIR /app

COPY dashboard/tablero_tiroides.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "tablero_tiroides.py", "--server.port=8501", "--server.address=0.0.0.0"]

